# Video 69
# El proposito de llamarse .dev es para diferenciarlo con el de produccon
# El de developer no ara un "$ npm run build" sino que ara un "$ npm run start"
### ==================================================== ###
###                 Specify a base image                 ###
### ==================================================== ###
FROM node:alpine

### ==================================================== ###
###               Install some dependencies              ###
### ==================================================== ###
WORKDIR '/app'

COPY package.json ./
RUN npm install
COPY ./ ./

### ==================================================== ###
###                    Default comands                   ###
### ==================================================== ###
CMD ["npm", "run", "start"]
